import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import DarkProvider from "./DarkProvider";
import Global from "./LayoutComponent";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "DASHBOARD Harf Hesab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en" dir="rtl" suppressHydrationWarning>
        <body className="bg-background dark:bg-background_dark">
          <Global>
            <DarkProvider>
              {children}
              <ToastContainer
                bodyClassName={'font-["iransans-md"] text-xs text-right dark:text-text_dark text-text'}
                rtl={true}
              />
            </DarkProvider>
          </Global>
        </body>
      </html>
    </ReduxProvider>
  );
}
